### ISSUE TITLE
更新MAA-v4.28.1-win-x64后无法启动，設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。

### ISSUE THREAD

**Issue by athtamis** [MaaAssistantArknights/MaaAssistantArknights#7601] opened 2023-12-14 20:26 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA 遇到了问题
設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。
已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
解决方案
出现未知错误
详细信息
System.Windows.Markup.XamlParseException: 設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。 ---> System.ArgumentException: 已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
   於 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   於 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   於 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(Object target, Object value)
   於 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   於 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   於 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   於 MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 System.Windows.ResourceDictionary.set_Source(Uri value)
   於 MaaWpfGui.Helper.LocalizationHelper.Load()
   於 MaaWpfGui.Main.Bootstrapper.OnStart()
   於 Stylet.BootstrapperBase.Start(String[] args)
   於 System.Windows.Application.OnStartup(StartupEventArgs e)
   於 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   於 System.Windows.Application.<.ctor>b__1_0(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

MAA-v4.28.0-win-x64仍能正常使用

### Log files

[2023-12-15 04:21:50.257] <1><> ===================================
[2023-12-15 04:21:50.274] <1><> MaaAssistantArknights GUI started
[2023-12-15 04:21:50.274] <1><> Version v4.28.1
[2023-12-15 04:21:50.276] <1><> Maa ENV: Production
[2023-12-15 04:21:50.276] <1><> User Dir U:\LSGM\MAA-v4.28.1-win-x64
[2023-12-15 04:21:50.277] <1><> Run as Administrator
[2023-12-15 04:21:50.277] <1><> ===================================
[2023-12-15 04:21:50.568] <1><> Unhandled exception
System.Windows.Markup.XamlParseException: 設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。 ---> System.ArgumentException: 已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
   於 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   於 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   於 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(Object target, Object value)
   於 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   於 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   於 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   於 MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 System.Windows.ResourceDictionary.set_Source(Uri value)
   於 MaaWpfGui.Helper.LocalizationHelper.Load()
   於 MaaWpfGui.Main.Bootstrapper.OnStart()
   於 Stylet.BootstrapperBase.Start(String[] args)
   於 System.Windows.Application.OnStartup(StartupEventArgs e)
   於 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   於 System.Windows.Application.<.ctor>b__1_0(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Screenshots

![QQ截图20231215042240](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11697509/5ec9f80d-893d-47db-9efa-67093bbce04b)

**Comment by Constrat** [comment] 2023-12-14 22:00
Don't open duplicates.
Duplicate of #7599

**Closed by Constrat** 2023-12-14 22:00 UTC
Labels: bug, client: WpfGui, module: others

**Comment by ABA2396** [comment] 2023-12-15 01:58
v4.28.2 fixed，可以先把 \config\gui.json 中的 "GUI.Localization" 的值改为 "zh-cn" 升级后换回来
