### ISSUE TITLE
最新版本的MAA会被WD报毒，且每次更新后又会重新报毒

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#6836] opened 2023-10-10 02:02 UTC
### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103177863/1b09dac7-3741-4c5a-be39-8f5159ca339c)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103177863/9ba95575-e861-4354-a592-766f3460c881)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103177863/716fc589-d970-4ad5-8559-f73aec9a66f0)

问题是可能是从~~v4.25.0-beta.1~~[v4.25.0-beta.2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.25.0-beta.2)开始出现的，我记不太清了，但是v4.24.0是没有问题的

**Comment by HS7097** [comment] 2023-10-10 02:03
分别来自两台电脑，因为在局域网内且已经做了网络磁盘映射，处理起来有点麻烦

**Comment by SherkeyXD** [comment] 2023-10-10 05:09
Duplicate of #6662

**Closed by SherkeyXD** 2023-10-10 05:09 UTC
Labels: question, ambiguous
