### ISSUE TITLE
[Global/EN] All special event (encounter) in Rougelike with WordOcr will be recognized as Unknown Event

### ISSUE THREAD

**Issue by zayn7lie** [MaaAssistantArknights/MaaAssistantArknights#10107] opened 2024-08-06 07:00 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [x] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

The bug is related to the bug [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10088). I also stuck in the encounter event *Eye For an Eye*. When I read the log `asst.log`, I found that the event is recognized correctly by `asst::WordOcr` but run as Unknown Event and try to click the first option which is not available (Requires Proof of Friendship)

![image](https://github.com/user-attachments/assets/61a20509-5981-4b2d-bd98-d9951cf0c9b7)

When I gave a deeper look into it, I found that not only *Eye For an Eye*, but also a bunch of encounter event such as *Gift of History*, *The Kind Puppet*, etc. are also recognized correctly but run as Unknown Event

### Version

Running python file under Linux directly. Do not have idea about checking version.

### Log files

For `Eye For an Eye`
```
[2024-08-06 13:54:28.932][INF][Px4e919][Tx21e5] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterJudgeOption"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1}
[2024-08-06 13:54:28.932][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::RoguelikeStageEncounterTaskPlugin","details":{},"subtask":"RoguelikeStageEncounterTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:28.932][TRC][Px4e919][Tx21e5] asst::RoguelikeStageEncounterTaskPlugin::_run | enter
[2024-08-06 13:54:28.932][TRC][Px4e919][Tx21e5] ready to sleep 600
[2024-08-06 13:54:29.532][TRC][Px4e919][Tx21e5] end of sleep 600
[2024-08-06 13:54:29.634][INF][Px4e919][Tx21e5] Call ` adb -s 192.168.240.112:5555 exec-out "screencap | nc -w 3 192.168.240.1 37245" ` ret 0 , cost 102 ms , stdout size: 0 , socket size: 3686416
[2024-08-06 13:54:30.361][TRC][Px4e919][Tx21e5] asst::WordOcr [{ Eye For an Eye: [ 78, 89, 168, 33 ], score: 0.947020 }, { A refined,well-dressed Sarkaz gentleman stands before you. He politely asks if you kn: [ 114, 127, 608, 18 ], score: 0.945221 }, { innocent man who was once wrongfully punished because of him.You ask him to elabc: [ 113, 148, 610, 18 ], score: 0.945169 }, { learn that,because of a mistake he made, the villagers all mistook his friend for a Vam: [ 113, 169, 611, 18 ], score: 0.932982 }, { locked him here. The man promises a sizable reward if you lend him your help: [ 113, 190, 553, 19 ], score: 0.937468 }] by OCR Pipeline , cost 724 ms
[2024-08-06 13:54:30.363][INF][Px4e919][Tx21e5] Unknown Event
[2024-08-06 13:54:30.363][TRC][Px4e919][Tx21e5] asst::RoguelikeStageEncounterTaskPlugin::_run | leave, 1431 ms
[2024-08-06 13:54:30.363][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::RoguelikeStageEncounterTaskPlugin","details":{},"subtask":"RoguelikeStageEncounterTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:30.363][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":40,"max_times":2147483647,"result":null,"task":"StageEncounterJudgeOption"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:30.363][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":40,"max_times":2147483647,"result":null,"task":"StageEncounterJudgeOption"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:30.363][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:54:30.863][TRC][Px4e919][Tx21e5] end of sleep 500
[2024-08-06 13:54:30.863][INF][Px4e919][Tx21e5] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterOptionFree","Phantom@Roguelike@StageEncounterOptionLeave","Phantom@Roguelike@ChooseOperFlag","Phantom@Roguelike@StageEmergencyDpsEnter","Phantom@Roguelike@StageCombatDpsEnter","Phantom@Roguelike@CloseEvent","Phantom@Roguelike@StageEncounterOptionUnknown","Phantom@Roguelike@NextLevel","Phantom@Roguelike@StageTrader","Phantom@Roguelike@StageSafeHouse","Phantom@Roguelike@StageEncounter","Phantom@Roguelike@StageBoons","Phantom@Roguelike@StageCombatDps","Phantom@Roguelike@StageEmergencyDps","Phantom@Roguelike@StageDreadfulFoe"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeOption","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1}
[2024-08-06 13:54:30.981][INF][Px4e919][Tx21e5] Call ` adb -s 192.168.240.112:5555 exec-out "screencap | nc -w 3 192.168.240.1 37245" ` ret 0 , cost 117 ms , stdout size: 0 , socket size: 3686416
[2024-08-06 13:54:30.991][TRC][Px4e919][Tx21e5] match_templ | Phantom@Roguelike@StageEncounterOptionFree.png score: 0.982499 rect: [ 1141, 188, 104, 85 ] roi: [ 1100, 0, 180, 700 ]
[2024-08-06 13:54:30.991][TRC][Px4e919][Tx21e5] analyze | MatchTemplate Phantom@Roguelike@StageEncounterOptionFree
[2024-08-06 13:54:30.992][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":9,"max_times":2147483647,"result":{"score":0.982499},"task":"StageEncounterOptionFree"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeOption","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:30.992][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:54:31.492][TRC][Px4e919][Tx21e5] end of sleep 500
[2024-08-06 13:54:31.492][TRC][Px4e919][Tx21e5] Click with scaled coordinates (1194, 238) 1
[2024-08-06 13:54:31.492][TRC][Px4e919][Tx21e5] maatouch click: (1194, 238)
[2024-08-06 13:54:31.592][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":9,"max_times":2147483647,"result":{"score":0.982499},"task":"StageEncounterOptionFree"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeOption","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:31.592][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:54:32.092][TRC][Px4e919][Tx21e5] end of sleep 500
[2024-08-06 13:54:32.092][INF][Px4e919][Tx21e5] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterLeaveConfirm","Phantom@Roguelike@StageEncounterOptionLeave","Phantom@Roguelike@NextLevel","Phantom@Roguelike@StageTrader","Phantom@Roguelike@StageSafeHouse","Phantom@Roguelike@StageEncounter","Phantom@Roguelike@StageBoons","Phantom@Roguelike@StageCombatDps","Phantom@Roguelike@StageEmergencyDps","Phantom@Roguelike@StageDreadfulFoe","Phantom@Roguelike@StageEncounterOptionFree","Phantom@Roguelike@ChooseOperFlag","Phantom@Roguelike@StageEmergencyDpsEnter","Phantom@Roguelike@StageCombatDpsEnter","Phantom@Roguelike@CloseEvent","Phantom@Roguelike@StageEncounterOptionUnknown"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionFree","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1}
[2024-08-06 13:54:32.185][INF][Px4e919][Tx21e5] Call ` adb -s 192.168.240.112:5555 exec-out "screencap | nc -w 3 192.168.240.1 37245" ` ret 0 , cost 93 ms , stdout size: 0 , socket size: 3686416
[2024-08-06 13:54:32.186][INF][Px4e919][Tx21e5] Assistant::append_callback | ConnectionInfo {"details":{"avg":103,"max":145,"min":87},"uuid":"5ba28778d86a1ec9","what":"ScreencapCost"}
[2024-08-06 13:54:32.285][TRC][Px4e919][Tx21e5] asst::WordOcr [{ ou.He politelv asks if vou know of: [ 2, 103, 237, 15 ], score: 0.942170 }, { of him.You ask him to elaborate : [ 3, 124, 237, 15 ], score: 0.933549 }] by OCR Pipeline , cost 83 ms
[2024-08-06 13:54:32.480][TRC][Px4e919][Tx21e5] match_templ | Phantom@Roguelike@StageSafeHouse.png score: 0.683011 rect: [ 1136, 500, 119, 44 ] roi: [ 0, 53, 1280, 554 ]
[2024-08-06 13:54:32.632][TRC][Px4e919][Tx21e5] match_templ | Phantom@Roguelike@StageBoons.png score: 0.684282 rect: [ 258, 312, 119, 46 ] roi: [ 0, 53, 1280, 554 ]
[2024-08-06 13:54:32.938][TRC][Px4e919][Tx21e5] match_templ | Phantom@Roguelike@StageDreadfulFoe.png score: 0.618131 rect: [ 523, 373, 203, 47 ] roi: [ 0, 53, 1280, 554 ]
[2024-08-06 13:54:32.948][TRC][Px4e919][Tx21e5] match_templ | Phantom@Roguelike@StageEncounterOptionFree.png score: 0.979102 rect: [ 1141, 188, 104, 85 ] roi: [ 1100, 0, 180, 700 ]
[2024-08-06 13:54:32.948][TRC][Px4e919][Tx21e5] analyze | MatchTemplate Phantom@Roguelike@StageEncounterOptionFree
[2024-08-06 13:54:32.948][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":10,"max_times":2147483647,"result":{"score":0.979102},"task":"StageEncounterOptionFree"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionFree","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:32.948][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:54:33.448][TRC][Px4e919][Tx21e5] end of sleep 500
[2024-08-06 13:54:33.448][TRC][Px4e919][Tx21e5] Click with scaled coordinates (1200, 223) 1
[2024-08-06 13:54:33.448][TRC][Px4e919][Tx21e5] maatouch click: (1200, 223)
[2024-08-06 13:54:33.548][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":10,"max_times":2147483647,"result":{"score":0.979102},"task":"StageEncounterOptionFree"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionFree","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:33.548][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:54:34.049][TRC][Px4e919][Tx21e5] end of sleep 500
... Start Repeating
```

For other special encounter event
```
[2024-08-06 13:54:09.519][INF][Px4e919][Tx21e5] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterJudgeOption"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1}
[2024-08-06 13:54:09.519][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::RoguelikeStageEncounterTaskPlugin","details":{},"subtask":"RoguelikeStageEncounterTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:09.519][TRC][Px4e919][Tx21e5] asst::RoguelikeStageEncounterTaskPlugin::_run | enter
[2024-08-06 13:54:09.519][TRC][Px4e919][Tx21e5] ready to sleep 600
[2024-08-06 13:54:10.120][TRC][Px4e919][Tx21e5] end of sleep 600
[2024-08-06 13:54:10.210][INF][Px4e919][Tx21e5] Call ` adb -s 192.168.240.112:5555 exec-out "screencap | nc -w 3 192.168.240.1 37245" ` ret 0 , cost 90 ms , stdout size: 0 , socket size: 3686416
[2024-08-06 13:54:11.373][TRC][Px4e919][Tx21e5] asst::WordOcr [{ Gift of History: [ 114, 74, 123, 24 ], score: 0.979351 }, { An old city once perished in a tragedy,and the tragic tale of the,citizens' tribulations: [ 112, 105, 607, 22 ], score: 0.944751 }, { weaved into a plav.While their storv continues to be told,the treasures of the citv ha: [ 115, 131, 607, 14 ], score: 0.949709 }, { dormant until now.You come across some treasures next to the rotten corpse of the s: [ 114, 152, 608, 14 ], score: 0.950642 }, { protagonist.The most precious manuscript, penned by the star herself,is half rotted a: [ 114, 171, 610, 17 ], score: 0.946836 }, { among the dust.: [ 112, 192, 116, 18 ], score: 0.974393 }] by OCR Pipeline , cost 1160 ms
[2024-08-06 13:54:11.376][INF][Px4e919][Tx21e5] Unknown Event
[2024-08-06 13:54:11.376][TRC][Px4e919][Tx21e5] asst::RoguelikeStageEncounterTaskPlugin::_run | leave, 1856 ms
[2024-08-06 13:54:11.376][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::RoguelikeStageEncounterTaskPlugin","details":{},"subtask":"RoguelikeStageEncounterTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:11.376][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":39,"max_times":2147483647,"result":null,"task":"StageEncounterJudgeOption"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:11.376][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":39,"max_times":2147483647,"result":null,"task":"StageEncounterJudgeOption"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:54:11.376][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:54:11.876][TRC][Px4e919][Tx21e5] end of sleep 500
```
```
[2024-08-06 13:50:54.783][INF][Px4e919][Tx21e5] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterJudgeOption"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1}
[2024-08-06 13:50:54.783][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::RoguelikeStageEncounterTaskPlugin","details":{},"subtask":"RoguelikeStageEncounterTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:50:54.783][TRC][Px4e919][Tx21e5] asst::RoguelikeStageEncounterTaskPlugin::_run | enter
[2024-08-06 13:50:54.783][TRC][Px4e919][Tx21e5] ready to sleep 600
[2024-08-06 13:50:55.383][TRC][Px4e919][Tx21e5] end of sleep 600
[2024-08-06 13:50:55.484][INF][Px4e919][Tx21e5] Call ` adb -s 192.168.240.112:5555 exec-out "screencap | nc -w 3 192.168.240.1 37245" ` ret 0 , cost 101 ms , stdout size: 0 , socket size: 3686416
[2024-08-06 13:50:56.160][TRC][Px4e919][Tx21e5] asst::WordOcr [{ The Kind Puppet: [ 81, 90, 178, 30 ], score: 0.956681 }, { A worn-out wooden puppet sits next to the wall, its limbs almost falling apart.Its haz: [ 113, 127, 610, 19 ], score: 0.938410 }, { features seem to ring a bell, but vou cannot sav for certain who it is given how worn-: [ 115, 151, 607, 14 ], score: 0.922842 }, { You come close to the puppet and find that there seems to be something hidden insid: [ 114, 169, 609, 18 ], score: 0.954786 }] by OCR Pipeline , cost 674 ms
[2024-08-06 13:50:56.161][INF][Px4e919][Tx21e5] Unknown Event
[2024-08-06 13:50:56.162][TRC][Px4e919][Tx21e5] asst::RoguelikeStageEncounterTaskPlugin::_run | leave, 1378 ms
[2024-08-06 13:50:56.162][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::RoguelikeStageEncounterTaskPlugin","details":{},"subtask":"RoguelikeStageEncounterTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:50:56.162][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":37,"max_times":2147483647,"result":null,"task":"StageEncounterJudgeOption"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:50:56.162][INF][Px4e919][Tx21e5] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":37,"max_times":2147483647,"result":null,"task":"StageEncounterJudgeOption"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterJudgeClick2","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":"5ba28778d86a1ec9"}
[2024-08-06 13:50:56.162][TRC][Px4e919][Tx21e5] ready to sleep 500
[2024-08-06 13:50:56.662][TRC][Px4e919][Tx21e5] end of sleep 500
```

### Configuration information

Emulator brand, emulator resolution: Container - Waydroid 1.4.2
Operating system: Arch Linux x86_64 (6.10.2-arch1-1)

**Comment by Daydreamer114** [comment] 2024-08-06 07:52
duplicate of #10088

**Closed by Daydreamer114** 2024-08-06 07:52 UTC
Labels: bug, module: infrast, module: roguelike
