### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by Boss1412** [MaaAssistantArknights/MaaAssistantArknights#9163] opened 2024-05-21 01:08 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
Attempted to perform an unauthorized operation.
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.IToastNotifierMethods.Show(IObjectReference _obj, ToastNotification notification)
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at MaaWpfGui.Helper.Notification.NotificationImplWinRT.ShowNotification(NotificationContent content)
   at MaaWpfGui.Helper.ToastNotification.Show(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationHint[] hints)
   at MaaWpfGui.Helper.ToastNotification.ShowRecruit(UInt32 row)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskExtraInfo(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15383089/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15383091/gui.log)

### 还有别的吗？

用的MUMU模拟器，这两天频繁出现这个问题，好像是升级MAA之后就开始出现了，摸不着头脑

**Comment by ABA2396** [comment] 2024-05-21 09:34
duplicate of  #9145

**Closed by ABA2396** 2024-05-21 09:34 UTC
Labels: bug, module: recruit, client: WpfGui
