### ISSUE TITLE
The type initializer for 'MaaWpfGui.Configuration.ConfigFactory' threw an exception.

### ISSUE THREAD

**Issue by MilkyChips** [MaaAssistantArknights/MaaAssistantArknights#6619] opened 2023-10-01 10:54 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [x] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA encountered an error
The type initializer for 'MaaWpfGui.Configuration.ConfigFactory' threw an exception.
The file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies could not be loaded. The manifest definition and assembly reference of the found assembly do not match. (HRESULT of the exception thrown: 0x80131040)
Workaround.
See the paragraph about crashes in the FAQ article.
Details
System.TypeInitializationException: The type initializer for 'MaaWpfGui.Configuration.ConfigFactory' threw an exception. ---> System.IO.FileLoadException: The file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies could not be loaded. The manifest definition and assembly reference for the found assembly do not match. (HRESULT: 0x80131040 with exception thrown)
   At: ObservableCollections.ObservableDictionary`2.set_Item(TKey key, TValue value)
   At: MaaWpfGui.Configuration.RootConfig.set_CurrentConfig(SpecificConfig value)
   At: MaaWpfGui.Configuration.ConfigFactory.<>c.<.cctor>b__18_0()
   Atch: System.Lazy`1.CreateValue()
   At: System.Lazy`1.LazyInitValue()
   At: MaaWpfGui.Configuration.ConfigFactory..cctor()
   --- End of internal exception stack trace
   At: MaaWpfGui.ViewModels.UI.SettingsViewModel.SwitchDarkMode()
   At: MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   Intrinsic: lambda_method(Closure , IRegistrationContext )
   In place of: StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   In place of: StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   Location: StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   Location: StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   At: StyletIoC.Internal.Container.Get[T](String key)
   In place of: MaaWpfGui.Helper.Instances.Instantiate (IContainer container)
   In place of: Stylet.BootstrapperBase.Start(String[] args)
   In place of System.Windows.Application.OnStartup (StartupEventArgs e)
   Location: MaaWpfGui.App.OnStartup (StartupEventArgs e)
   Location: System.Windows.Application.<.ctor>b__1_0 (Object unused)
   In place of System.Windows.Threading.ExceptionWrapper.InternalRealCall (Delegate callback, Object args, Int32 numArgs)
   In place of: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Translated with www.DeepL.com/Translator (free version)

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776976/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776977/gui.log)

**Comment by zzyyyl** [comment] 2023-10-01 11:10
duplicate of #6610

**Closed by zzyyyl** 2023-10-01 11:10 UTC
Labels: bug, module: GUI, module: others
