### ISSUE TITLE
Windows Defender 又开始给 Maa 报毒了

### ISSUE THREAD

**Issue by Lixuhuilll** [MaaAssistantArknights/MaaAssistantArknights#7561] opened 2023-12-13 11:13 UTC
### 说说你遇到的问题？

Windows Defender 又开始给 Maa 报毒了，版本为 v4.28.0-beta.2

![屏幕截图 2023-12-13 190834](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88485037/60afb157-940d-4f5a-8ba8-610b83fde832)
![屏幕截图 2023-12-13 190812](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88485037/1ecca3d5-5499-447a-94c4-8f5c07500f7f)

**Comment by Constrat** [comment] 2023-12-13 11:51
Nothing we can do.
Costura Fody still gives as issues. We are waiting for .NET8 to hopefullly fix this.

**Comment by Constrat** [comment] 2023-12-13 11:52
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662

**Closed by Constrat** 2023-12-13 11:52 UTC
Labels: question, ambiguous
