### ISSUE TITLE
IS4 get stuck in initial recruitment

### ISSUE THREAD

**Issue by Abolfazl137791** [MaaAssistantArknights/MaaAssistantArknights#8687] opened 2024-03-22 23:00 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

After starting Roguelike mode, MAA will go with "Over coming your weaknesses" then after choosing La Pluma, MAA will stop moving to the supporter recruitment and after some time, will abandon the exploration and start again to stuck in the same place.

### Version

Resource Version: Come Catastrophes or Wakes of Vultures
UI Version: v5.2.1-alpha.1.d074.g558f35e39
Core Version: v5.2.1-alpha.1.d074.g558f35e39

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14729147/asst.log)

### Anthing else?

I am using latest nightly updates with Mumu player 12.

**Comment by Constrat** [comment] 2024-03-23 08:25
Duplicate of #8632

**Closed by Constrat** 2024-03-23 08:25 UTC
Labels: bug, module: roguelike
