### ISSUE TITLE
[Global/EN] Stuck after investment in Phantom roguelike

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10012] opened 2024-08-01 10:22 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

```python
[2024-08-01 17:54:43.573][INF][Px9be8][Txa7c0] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterLeaveConfirm","Phantom@Roguelike@StageEncounterOptionFree","Phantom@Roguelike@NextLevel","Phantom@Roguelike@StageTrader","Phantom@Roguelike@StageSafeHouse","Phantom@Roguelike@StageEncounter","Phantom@Roguelike@StageBoons","Phantom@Roguelike@StageCombatDps","Phantom@Roguelike@StageEmergencyDps","Phantom@Roguelike@StageDreadfulFoe","Phantom@Roguelike@StageEncounterOptionLeave","Phantom@Roguelike@ChooseOperFlag","Phantom@Roguelike@StageEmergencyDpsEnter","Phantom@Roguelike@StageCombatDpsEnter","Phantom@Roguelike@CloseEvent","Phantom@Roguelike@StageEncounterOptionUnknown"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionUnknown","subtask":"ProcessTask","taskchain":"Roguelike","taskid":20}
[2024-08-01 17:54:43.691][TRC][Px9be8][Txa7c0] asst::WordOcr [{ Price: [ 44, 17, 35, 20 ], score: 0.998064 }, { 16: [ 29, 33, 51, 39 ], score: 0.999127 }] by OCR Pipeline , cost 77 ms
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] match_templ | Phantom@Roguelike@StageEncounterOptionUnknown.png score: 0.955917 rect: [ 1132, 37, 100, 12 ] roi: [ 1100, 0, 180, 700 ]
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] asst::PipelineAnalyzer::analyze | MatchTemplate Phantom@Roguelike@StageEncounterOptionUnknown
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] asst::ScreenshotTaskPlugin::verify | task Phantom@Roguelike@StageEncounterOptionUnknown triggered recently, skip
[2024-08-01 17:54:44.474][INF][Px9be8][Txa7c0] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":21,"max_times":2147483647,"result":{"score":0.955917},"task":"StageEncounterOptionUnknown"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionUnknown","subtask":"ProcessTask","taskchain":"Roguelike","taskid":20,"uuid":"ced43e55f751740a"}
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] ready to sleep 500
[2024-08-01 17:54:44.975][TRC][Px9be8][Txa7c0] end of sleep 500
[2024-08-01 17:54:44.975][TRC][Px9be8][Txa7c0] Click with scaled coordinates (1172, 42) 1.5
[2024-08-01 17:54:44.975][TRC][Px9be8][Txa7c0] minitouch click: (1758, 63)
[2024-08-01 17:54:45.076][INF][Px9be8][Txa7c0] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":21,"max_times":2147483647,"result":{"score":0.955917},"task":"StageEncounterOptionUnknown"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionUnknown","subtask":"ProcessTask","taskchain":"Roguelike","taskid":20,"uuid":"ced43e55f751740a"}
[2024-08-01 17:54:45.076][TRC][Px9be8][Txa7c0] ready to sleep 500
[2024-08-01 17:54:45.577][TRC][Px9be8][Txa7c0] end of sleep 500
```

### Version

![image](https://github.com/user-attachments/assets/5a3ebd9a-f736-41cb-9644-1763dfc2c60c)

### 日志文件

![image](https://github.com/user-attachments/assets/2764fedb-ef3f-4b77-afbc-e2f65a733da0)
[asst.bak - 副本.log](https://github.com/user-attachments/files/16454653/asst.bak.-.log)

### 截图

![MuMu12-20240801-180901](https://github.com/user-attachments/assets/17484ff5-4ed3-4e1a-959f-786422f13985)
[MuMu12-20240801-180901.zip](https://github.com/user-attachments/files/16454630/MuMu12-20240801-180901.zip)

**Comment by Constrat** [comment] 2024-08-01 10:46
@Manicsteiner Were there changes also inside the I.S. trader? I remember some fixes were pushed for the Official client

**Comment by Constrat** [comment] 2024-08-01 11:17
Wait wait, why is the screen 
![image](https://github.com/user-attachments/assets/ebfaa27f-77ba-4114-918b-a4d6cd70f8c8)
2340x1080?

**Comment by Daydreamer114** [comment] 2024-08-01 11:17
![image](https://github.com/user-attachments/assets/949def70-ca54-4319-b763-b9b61e3ab986)
dont trust the log :(

**Comment by Constrat** [comment] 2024-08-01 11:19
Uhm, I did this run with Sami, could it be different themes? Seems pretty stupid, but knowing Yostar...

**Comment by Daydreamer114** [comment] 2024-08-01 11:21
It's Phantom

> Uhm, I did this run with Sami, could it be different themes? Seems pretty stupid, but knowing Yostar...

**Comment by Daydreamer114** [comment] 2024-08-01 11:22
```python
[2024-08-01 17:54:43.573][INF][Px9be8][Txa7c0] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@StageEncounterLeaveConfirm","Phantom@Roguelike@StageEncounterOptionFree","Phantom@Roguelike@NextLevel","Phantom@Roguelike@StageTrader","Phantom@Roguelike@StageSafeHouse","Phantom@Roguelike@StageEncounter","Phantom@Roguelike@StageBoons","Phantom@Roguelike@StageCombatDps","Phantom@Roguelike@StageEmergencyDps","Phantom@Roguelike@StageDreadfulFoe","Phantom@Roguelike@StageEncounterOptionLeave","Phantom@Roguelike@ChooseOperFlag","Phantom@Roguelike@StageEmergencyDpsEnter","Phantom@Roguelike@StageCombatDpsEnter","Phantom@Roguelike@CloseEvent","Phantom@Roguelike@StageEncounterOptionUnknown"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionUnknown","subtask":"ProcessTask","taskchain":"Roguelike","taskid":20}
[2024-08-01 17:54:43.691][TRC][Px9be8][Txa7c0] asst::WordOcr [{ Price: [ 44, 17, 35, 20 ], score: 0.998064 }, { 16: [ 29, 33, 51, 39 ], score: 0.999127 }] by OCR Pipeline , cost 77 ms
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] match_templ | Phantom@Roguelike@StageEncounterOptionUnknown.png score: 0.955917 rect: [ 1132, 37, 100, 12 ] roi: [ 1100, 0, 180, 700 ]
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] asst::PipelineAnalyzer::analyze | MatchTemplate Phantom@Roguelike@StageEncounterOptionUnknown
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] asst::ScreenshotTaskPlugin::verify | task Phantom@Roguelike@StageEncounterOptionUnknown triggered recently, skip
[2024-08-01 17:54:44.474][INF][Px9be8][Txa7c0] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":21,"max_times":2147483647,"result":{"score":0.955917},"task":"StageEncounterOptionUnknown"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionUnknown","subtask":"ProcessTask","taskchain":"Roguelike","taskid":20,"uuid":"ced43e55f751740a"}
[2024-08-01 17:54:44.474][TRC][Px9be8][Txa7c0] ready to sleep 500
[2024-08-01 17:54:44.975][TRC][Px9be8][Txa7c0] end of sleep 500
[2024-08-01 17:54:44.975][TRC][Px9be8][Txa7c0] Click with scaled coordinates (1172, 42) 1.5
[2024-08-01 17:54:44.975][TRC][Px9be8][Txa7c0] minitouch click: (1758, 63)
[2024-08-01 17:54:45.076][INF][Px9be8][Txa7c0] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":21,"max_times":2147483647,"result":{"score":0.955917},"task":"StageEncounterOptionUnknown"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterOptionUnknown","subtask":"ProcessTask","taskchain":"Roguelike","taskid":20,"uuid":"ced43e55f751740a"}
[2024-08-01 17:54:45.076][TRC][Px9be8][Txa7c0] ready to sleep 500
[2024-08-01 17:54:45.577][TRC][Px9be8][Txa7c0] end of sleep 500
```
I may have uploaded a wrong part of the log at the beginning

**Comment by Constrat** [comment] 2024-08-01 11:22
Yeah I noticed, I'm checking the entire log now, my bad

**Comment by Constrat** [comment] 2024-08-01 11:32
Phantom@Roguelike@StageEncounterOptionUnknown.png score: 0.955917
Ok this is very strange. To be honest, as Phantom I.S. is super old there could be some bugs here and there, and especially after version change new bugs might appear. When I'll have time I'll take a look, but I don't guarantee anything.

**Comment by Daydreamer114** [comment] 2024-08-01 11:33
[Phantom@Roguelike@StageEncounterOptionUnknown.png]
![Phantom@Roguelike@StageEncounterOptionUnknown](https://github.com/user-attachments/assets/fdf0fcb4-9926-4338-a9bb-db8a466d1deb)
Hard to understand what is this.
i'll try again

**Comment by Daydreamer114** [comment] 2024-08-01 11:34
Resource Version: Here A People Sows
what a beautiful translate

**Comment by Constrat** [comment] 2024-08-01 11:34
That's a super precise png with a precise ROI that is used when identifying encounters.
In case the OCR does not detect and replace a correct string of text from the `encounter.json` it will try to identify that and it will click it, it's the "default option" and it was first used before we used all the encounter logic to detect text, and decide what choice.

**Comment by Constrat** [comment] 2024-08-01 11:36
> Resource Version: Here A People Sows what a beautiful translate

This is what I hate about Yostar.
- Shitty servers
- The client is half as fast as the Hypergryph one (no idea how considering they should just translate)
- The translations are atrocious
- And the translations have so many errors it's insane, missing spaces ` `, xaml tags out of nowhere, it's incredible.

**Comment by Daydreamer114** [comment] 2024-08-01 11:50
> * The translations are atrocious
> * And the translations have so many errors it's insane, missing spaces ` `, xaml tags out of nowhere, it's incredible.

Just for the version name, it's hard to translate "怀黍离" directly. "怀" as embracing, taking, "黍" generally for plants, specifically "millet", "离" means leaving. This translate makes things easy but that's all of the story. Chinese have their special emotion on rice, sowing and harvesting brings people vitality. What's more, there's a great man in China improved rice varieties and fed many people. That's why this story means a log to us.


> * And the translations have so many errors it's insane, missing spaces ` `, xaml tags out of nowhere, it's incredible.

And also little charactors in Sami even not recognizable for human, I hate this either.

**Comment by Daydreamer114** [comment] 2024-08-01 12:12
I'll keep trying to recurrence this issue. Until now, it only happened once.

**Comment by Manicsteiner** [comment] 2024-08-01 15:13
> Were there changes also inside the I.S. trader? I remember some fixes were pushed for the Official client

It looks like everything in I.S. is working fine for me

**Comment by Constrat** [comment] 2024-08-01 15:14
Yeah, sorry for the @ it seems to be one off / hard to reproduce as I also wasn't able to reproduce it in Sami.

**Comment by Daydreamer114** [comment] 2024-08-04 02:21
![MuMu12-20240804-095703](https://github.com/user-attachments/assets/fe628d77-a46d-4c60-8e87-aaf3a88693e5)
[gui.log](https://github.com/user-attachments/files/16484494/gui.log)
[asst - 副本.log](https://github.com/user-attachments/files/16484562/asst.-.log)

**Comment by Daydreamer114** [comment] 2024-08-04 03:22
@Constrat I finally get this.
This is line 210 in asst.log:
```python
2024-08-04 02:23:32.897][INF][Pxd300][Txd3c4] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@TraderRandomShopping","Phantom@Roguelike@StageTraderLeave","Phantom@Roguelike@DropsFlag","Phantom@Roguelike@ClickToDrops"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterGiveUpRecruitConfirm","subtask":"ProcessTask","taskchain":"Roguelike","taskid":16}
[2024-08-04 02:23:33.062][INF][Pxd300][Txd3c4] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickRect","algorithm":"JustReturn","exec_times":11,"max_times":2147483647,"result":null,"task":"ClickToDrops"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterGiveUpRecruitConfirm","subtask":"ProcessTask","taskchain":"Roguelike","taskid":16,"uuid":"ced43e55f751740a"}
[2024-08-04 02:23:33.062][TRC][Pxd300][Txd3c4] Click with scaled coordinates (622, 623) 1.5
[2024-08-04 02:23:33.062][TRC][Pxd300][Txd3c4] minitouch click: (933, 934)
[2024-08-04 02:23:33.163][TRC][Pxd300][Txd3c4] ready to sleep 500
[2024-08-04 02:23:33.664][TRC][Pxd300][Txd3c4] end of sleep 500
[2024-08-04 02:23:33.664][INF][Pxd300][Txd3c4] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickRect","algorithm":"JustReturn","exec_times":11,"max_times":2147483647,"result":null,"task":"ClickToDrops"},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@StageEncounterGiveUpRecruitConfirm","subtask":"ProcessTask","taskchain":"Roguelike","taskid":16,"uuid":"ced43e55f751740a"}
[2024-08-04 02:23:33.664][TRC][Pxd300][Txd3c4] ready to sleep 500
[2024-08-04 02:23:34.164][TRC][Pxd300][Txd3c4] end of sleep 500
```
BUT, due to the network, Arknights is in this interface:
<img width="1280" alt="61cab00908b13150f8fe105698c2638" src="https://github.com/user-attachments/assets/1bc01812-ea0a-4b39-831f-90cfd411ff78">

SO none of first three tasks is succeed:
<img width="407" alt="f731af55ff89b4ffff9cd4c764fab0b" src="https://github.com/user-attachments/assets/83fe1d95-d85a-481b-bb05-18f1395af39a">

The "ClickToDrops" is a task with JustReturn:
<img width="408" alt="2765bf19973de97694c62f0a27e41a3" src="https://github.com/user-attachments/assets/18b4abef-3589-48a0-a9f2-bb6f4042f73a">

makes maa thinks the shopping is exited.

--------------------------

I would like to ask for your opinion for how to fix this.
My solution is to add a check in the "next" of "ClickToDrops":
```python
    "Roguelike@ClickToDrops": {
        "algorithm": "JustReturn",
        "action": "ClickRect",
        "specificRect": [600, 600, 50, 50],
        "postDelay": 500,
        "next": [
            "Roguelike@DropsFlag",
            "Roguelike@ChooseOperFlag",
            "Roguelike@StageEncounterSpecialClose",
            "Roguelike@TraderRandomShopping",
            "Roguelike@StageTraderLeave",
            "Roguelike@Stages#next",
            "Roguelike@StartUpThemes#next",
            "Roguelike@StageEncounterGiveUpRecruit", //Add this line
            "Roguelike@ClickToDrops"
        ]
    },

**Comment by Constrat** [comment] 2024-08-04 09:12
Then this should be an issue even for other clients no?

**Comment by Daydreamer114** [comment] 2024-08-04 09:44
Sorry this isn't an issue after investment:(  I misunderstood it
And my new issue is not only for English, it is also for other clients. It happens when Internet lag happens.
I am considering create a new task chain for quiting recruitment when investment,  rather than reuse task chain of recruitment when getting drops

I got another investment issue's log and I will upload it later

**Comment by Constrat** [comment] 2024-08-04 09:46
I suggest just closing this one and making a completely new issue, since:
- 1 It's for all client
- 2 It's network related (meaning can happen everywhere)
- Just start with a clean slate and give all videos and logs directly there :)

**Closed by Constrat** 2024-08-04 09:46 UTC
Labels: bug, module: roguelike, help wanted, keep-open
