### ISSUE TITLE
国际服自动肉鸽不能处理大锁前置事件

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#3975] opened 2023-03-13 00:23 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在v4.12.1-rc.1运行自动肉鸽，选择了远程战术，并自定义凯尔希开局，多数情况下运行正常，但是当希望为0时正好进入大锁的前置事件（减1希望拿玩偶或者加1希望离开）时，就会卡住。重新开始运行如果碰到上述情况仍会卡住。时间点应该是在[16:14:36]左右。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10952501/asst.log)

### 截图

![Screenshot_2023 03 12_17 01 38 966](https://user-images.githubusercontent.com/65427501/224582446-42a6a6e3-91cd-4bdf-b8cc-8a0d63744dea.png)

### 还有别的吗？

蓝叠5.0.230，1280x720， 320 dpi

**Comment by skzidan** [comment] 2023-03-13 05:23
can you send me the screenshot of your MAA IS setting ? 
![image](https://user-images.githubusercontent.com/37244053/224614701-0bab11a4-b873-4f29-86a7-70f22da63e54.png)

**Comment by BlackNorton** [comment] 2023-03-13 05:47
> can you send me the screenshot of your MAA IS setting ? ![image](https://user-images.githubusercontent.com/37244053/224614701-0bab11a4-b873-4f29-86a7-70f22da63e54.png)

![2023-03-12 22_45_26-MAA - v4 12 1-rc 1 - 蓝叠模拟器 (127 0 0 1_5555) - 国际服 (YoStarEN)](https://user-images.githubusercontent.com/65427501/224617963-aa130b74-5021-44cc-ac19-77fb71e62266.png)

**Comment by liuyifan-eric** [comment] 2023-03-13 18:22
This is a known issue but we haven't figured out how to fix it. We would be grateful if you could help us look into that

**Comment by BlackNorton** [comment] 2023-03-15 03:38
> This is a known issue but we haven't figured out how to fix it. We would be grateful if you could help us look into that

Should I provide more asst.log if I encounter this issue again?

**Comment by qaz1qazlol2** [comment] 2023-03-16 08:20
> > This is a known issue but we haven't figured out how to fix it. We would be grateful if you could help us look into that
> 
> Should I provide more asst.log if I encounter this issue again?

我看看我能不能再加几个关于肉鸽的截图来修复这个，我每日代理en服时也有这个问题，所以我干脆把自动肉鸽关掉了

**Comment by Constrat** [comment] 2023-08-18 17:12
duplicate #3433

**Comment by Constrat** [comment] 2023-08-18 17:13
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3433

**Comment by Constrat** [comment] 2023-08-18 17:14
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3433

**Closed by Constrat** 2023-08-18 17:14 UTC
Labels: bug, module: roguelike, duplicate, Client: EN
