### ISSUE TITLE
内测版v4.25.0-beta.1.d060.g669801ed7无法启动

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#6797] opened 2023-10-08 21:09 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题所示，更新到最新的内测版（v4.25.0-beta.1.d060.g669801ed7）后无法启动maa软件

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841778/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841779/asst.log)
约为05:00左右启动失败

**Comment by NosVladimir** [comment] 2023-10-08 22:06
同，windows defender报了木马，加入白名单后也无法启动，也不产生新的asset.log和gui.log了

**Comment by status102** [comment] 2023-10-08 23:55
最新版本为d063，而非d060，请更新至最新测试版

**Comment by SteveXu9102** [comment] 2023-10-09 00:00
Github Releases下载v4.25.0-beta.1(commit dcd6abd)进行手动更新后出现相同问题

**Comment by Horizon101011** [comment] 2023-10-09 00:02
不确定版本号（但应该是最新版，已经打不开了），更新后maa重启失败
事件查看器给出
```
应用程序: MAA.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.Xaml.XamlParseException
   在 MS.Internal.Xaml.Context.ObjectWriterContext.ServiceProvider_Resolve(System.String)
   在 MS.Internal.Markup.StaticExtension.ProvideValue(System.IServiceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)

异常信息: System.Xaml.XamlObjectWriterException
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)
   在 System.Xaml.XamlObjectWriter.Logic_ProvideValue(MS.Internal.Xaml.Context.ObjectWriterContext)
   在 System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(MS.Internal.Xaml.Context.ObjectWriterContext)
   在 System.Xaml.XamlObjectWriter.WriteEndObject()
   在 System.Xaml.XamlServices.Transform(System.Xaml.XamlReader, System.Xaml.XamlWriter, Boolean)
   在 System.Windows.ResourceDictionary.EvaluateMarkupExtensionNodeList(System.Xaml.XamlReader, System.IServiceProvider)
   在 System.Windows.ResourceDictionary.GetKeyValue(System.Windows.Baml2006.KeyRecord, System.IServiceProvider)
   在 System.Windows.ResourceDictionary.SetKeys(System.Collections.Generic.IList`1<System.Windows.Baml2006.KeyRecord>, System.IServiceProvider)
   在 System.Windows.Baml2006.WpfSharedBamlSchemaContext+<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(System.Object, System.Object)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)

异常信息: System.Windows.Markup.XamlParseException
   在 System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   在 System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   在 System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   在 MaaWpfGui.App.Main()


```

**Comment by KUAPT** [comment] 2023-10-09 00:05
> 最新版本为d063，而非d060，请更新至最新测试版

自动更新到最新版本后也出现了无法打开的问题

**Comment by SteveXu9102** [comment] 2023-10-09 00:06
以下为相应内存转储文件的分析：

----------------------------------------------------------------------------
The user dump currently examined is a minidump. Consequently, only a subset
of sos.dll functionality will be available. If needed, attaching to the live
process or debugging a full dump will allow access to sos.dll's full feature
set.
To create a full user dump use the command: .dump /ma <filename>
----------------------------------------------------------------------------
ntdll!NtWaitForMultipleObjects+0x14:
00007ffa`954afdb4 c3              ret
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Check Image - Checksum mismatch - Dump: 0x3b19cb, File: 0x3b3057 - C:\ProgramData\Dbg\sym\KERNELBASE.dll\C0C1B2293a6000\KERNELBASE.dll
*** WARNING: Unable to verify checksum for PresentationFramework.ni.dll
*** WARNING: Unable to verify checksum for System.Xaml.ni.dll
*** WARNING: Unable to verify checksum for MAA.exe
DEBUG_FLR_EXCEPTION_CODE(80131500) and the ".exr -1" ExceptionCode(e0434352) don't match

KEY_VALUES_STRING: 1

    Key  : Analysis.Elapsed.mSec
    Value: 14949

    Key  : Analysis.IO.Other.Mb
    Value: 0

    Key  : Analysis.IO.Read.Mb
    Value: 1

    Key  : Analysis.IO.Write.Mb
    Value: 0

    Key  : Analysis.Init.CPU.mSec
    Value: 15

    Key  : Analysis.Init.Elapsed.mSec
    Value: 5134

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 370

    Key  : CLR.BuiltBy
    Value: NET481REL1LAST_C

    Key  : CLR.Engine
    Value: CLR

    Key  : CLR.Exception.System.Windows.Markup.XamlParseException._lineNumber
    Value: 0n00000000000

    Key  : CLR.Exception.System.Windows.Markup.XamlParseException._linePosition
    Value: 0n00000000000

    Key  : CLR.Exception.System.Windows.Markup.XamlParseException._message
    Value: 设置属性“System.Windows.ResourceDictionary.DeferrableContent”时引发了异常。

    Key  : CLR.Exception.System.Xaml.XamlObjectWriterException._message
    Value: 设置属性“System.Windows.ResourceDictionary.Source”时引发了异常。

    Key  : CLR.Exception.System.Xaml.XamlParseException._message
    Value: 类型引用无法找到名为“{clr-namespace:Markdig.Wpf;assembly=Markdig.Wpf}Styles”的类型。

    Key  : CLR.Exception.Type
    Value: System.Xaml.XamlParseException

    Key  : CLR.Version
    Value: 4.8.9181.0

    Key  : Failure.Bucket
    Value: CLR_EXCEPTION_System.Xaml.XamlParseException_80131500_PresentationFramework.dll!MS.Internal.Markup.StaticExtension.ProvideValue

    Key  : Failure.Hash
    Value: {9fd8fb62-3863-5d16-b043-7e25a554b01a}

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 953060

    Key  : Timeline.Process.Start.DeltaSec
    Value: 2

    Key  : WER.OS.Branch
    Value: ni_release

    Key  : WER.OS.Version
    Value: 10.0.22621.1

    Key  : WER.Process.Version
    Value: 1.0.0.0


FILE_IN_CAB:  MAA.exe.48812.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  000000cd3efeff90 -- (.cxr 0xcd3efeff90)
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000000000
rdx=0000000000000000 rsi=00007ffa7265e188 rdi=000001dcad8712e8
rip=00007ffa725fb295 rsp=0000000000000000 rbp=000001dcaf940568
 r8=0000000000000002  r9=0000000000000002 r10=0000000000000000
r11=000001dcad724820 r12=00007ffa6faa41fe r13=00007ffa38cb3f44
r14=0000000000000000 r15=000001dcaf940568
iopl=0         nv up di pl nz na pe nc
cs=0000  ss=0000  ds=0000  es=0000  fs=0000  gs=0000             efl=00000000
clr!CreateHandleCommon+0x2d:
00007ffa`725fb295 488bc3          mov     rax,rbx
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffa92994ffc (KERNELBASE!RaiseException+0x000000000000006c)
   ExceptionCode: e0434352 (CLR exception)
  ExceptionFlags: 00000081
NumberParameters: 5
   Parameter[0]: ffffffff80131501
   Parameter[1]: 0000000000000000
   Parameter[2]: 0000000000000000
   Parameter[3]: 0000000000000000
   Parameter[4]: 00007ffa72540000

PROCESS_NAME:  MAA.exe

EXCEPTION_CODE_STR:  80131500

FAULTING_THREAD:  ffffffff

STACK_TEXT:  
000000cd`3effd370 00007ffa`38e1b4b0 System_Xaml_ni!MS.Internal.Xaml.Context.ObjectWriterContext.ServiceProvider_Resolve+0x16fbd0
000000cd`3effd3b0 00007ffa`016c2575 PresentationFramework_ni!MS.Internal.Markup.StaticExtension.ProvideValue+0xe5
000000cd`3effd400 00007ffa`38ccd32d System_Xaml_ni!MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue+0x2d


STACK_COMMAND:  !C:\ProgramData\Dbg\sym\SOS_AMD64_AMD64_4.8.9181.00.dll\64B854789a4000\SOS_AMD64_AMD64_4.8.9181.00.dll.pe 0x1dcaf93ae60 ; ** Pseudo Context ** ManagedPseudo ** Value: ffffffff ** ; kb

SYMBOL_NAME:  PresentationFramework_ni!MS.Internal.Markup.StaticExtension.ProvideValue+e5

MODULE_NAME: PresentationFramework

IMAGE_NAME:  PresentationFramework.dll

FAILURE_BUCKET_ID:  CLR_EXCEPTION_System.Xaml.XamlParseException_80131500_PresentationFramework.dll!MS.Internal.Markup.StaticExtension.ProvideValue

OS_VERSION:  10.0.22621.1

BUILDLAB_STR:  ni_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {9fd8fb62-3863-5d16-b043-7e25a554b01a}

Followup:     MachineOwner
---------

**Comment by status102** [comment] 2023-10-09 00:16
> 不确定版本号（但应该是最新版，已经打不开了），更新后maa重启失败
> 事件查看器给出
> ```
> 应用程序: MAA.exe
> Framework 版本: v4.0.30319
> 说明: 由于未经处理的异常，进程终止。
> 异常信息: System.Xaml.XamlParseException
>    在 MS.Internal.Xaml.Context.ObjectWriterContext.ServiceProvider_Resolve(System.String)
>    在 MS.Internal.Markup.StaticExtension.ProvideValue(System.IServiceProvider)
>    在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)
> 
> 异常信息: System.Xaml.XamlObjectWriterException
>    在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(System.Windows.Markup.MarkupExtension, System.IServiceProvider)
>    在 System.Xaml.XamlObjectWriter.Logic_ProvideValue(MS.Internal.Xaml.Context.ObjectWriterContext)
>    在 System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(MS.Internal.Xaml.Context.ObjectWriterContext)
>    在 System.Xaml.XamlObjectWriter.WriteEndObject()
>    在 System.Xaml.XamlServices.Transform(System.Xaml.XamlReader, System.Xaml.XamlWriter, Boolean)
>    在 System.Windows.ResourceDictionary.EvaluateMarkupExtensionNodeList(System.Xaml.XamlReader, System.IServiceProvider)
>    在 System.Windows.ResourceDictionary.GetKeyValue(System.Windows.Baml2006.KeyRecord, System.IServiceProvider)
>    在 System.Windows.ResourceDictionary.SetKeys(System.Collections.Generic.IList`1<System.Windows.Baml2006.KeyRecord>, System.IServiceProvider)
>    在 System.Windows.Baml2006.WpfSharedBamlSchemaContext+<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(System.Object, System.Object)
>    在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)
> 
> 异常信息: System.Windows.Markup.XamlParseException
>    在 System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
>    在 System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
>    在 System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
>    在 System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
>    在 MaaWpfGui.App.Main()
> 
> 
> ```
> 

该问题已知d060会触发

**Comment by SwissRollC** [comment] 2023-10-09 00:24
自动更新只更新至d060，手动下载安装d060→d063问题解决

**Comment by SteveXu9102** [comment] 2023-10-09 00:28
版本回退到4.24后选择内测版通道进行更新，注意到OTA包版本是d060

**Comment by SherkeyXD** [comment] 2023-10-09 02:07
Duplicate of #6761

**Closed** 2023-10-09 02:09 UTC
Labels: bug, fixed, module: GUI, duplicate
