### ISSUE TITLE
建议肉鸽烧水允许自选难度

### ISSUE THREAD

**Issue by minkuuuu** [MaaAssistantArknights/MaaAssistantArknights#9660] opened 2024-07-14 03:33 UTC
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

I want to grind all squad all ending medals with hot water kettle as a starting collectible but only need it at Braving Nature 12, the preset was left at Braving Nature 15 and it is too much for me to handle. I have to stop the progress manually at the 2nd start before MAA choose Braving Nature 15

### Any good ideas?

Probably not swiping all to the top I guess. Let user choose which level they want to have the Hot Water Kettle from the MAA UI

### Additional

![MuMu12-20240713-233326](https://github.com/user-attachments/assets/457fb9cf-8f72-4d39-a882-5880ffc05854)

**Comment by Constrat** [comment] 2024-07-14 09:20
I don't understand. You farm for the Hot Water Kettle at an easy difficulty. You switch to 12 and play normally. Profit no?

Instead, you want MAA to automatically choose the difficulty for you after farming the Hot Water Kettle and then also play later at diff 12.

**Comment by zzyyyl** [comment] 2024-07-14 09:42
Similar issue:

- #9080
- #8926

其实搁置的主要原因是，没人写自选难度：）

**Comment by status102** [comment] 2024-07-15 11:06
DUplicate of #9080

**Closed by status102** 2024-07-15 11:06 UTC
Labels: enhancement, module: roguelike
