### ISSUE TITLE
后每次启动更新游戏资源都失败

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#7321] opened 2023-11-16 04:12 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，更新之后还被windows defender杀了一次，从里头restore出来发现更新资源失败，截图放下面了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13372127/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13372128/gui.log)

### 截图

<img width="399" alt="maa1" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/98ce570a-f1b2-4c5a-a7b6-1218fc5d7304">
<img width="398" alt="maa2" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/e80984dd-3650-4a03-a692-f510ace36465">
<img width="355" alt="maa3" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/2e6b4b8a-caf6-40b9-b6ed-2e32dd20cec7">

### 还有别的吗？

Win11 10.0.22631 Build 22631
MAA v4.27.0-beta.1

**Comment by ABA2396** [comment] 2023-11-16 06:00
```
[2023-11-15 22:08:34.656] <1><> HTTP: OK GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
[2023-11-15 22:08:35.213] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/dynamic_list.txt
[2023-11-15 22:08:36.857] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/overview.json
[2023-11-15 22:08:38.367] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/stages.json
[2023-11-15 22:08:54.407] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
```

**Comment by Astesia-poi** [comment] 2023-11-16 15:26
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85828572/08fccb3d-30fb-4fc8-b262-3ad5fda8b855)
我也有这个问题，也是卡在2/18

**Comment by vonnoq** [comment] 2023-11-16 17:53
這兩個狀況我也有遇到

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13381010/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13381023/asst.log)

**Comment by yangalan123** [comment] 2023-11-16 17:58
我试了一下，如果是老版本升级会遇到这个问题，我完全重新下载beta.1，解压到另外一个地方，然后运行就行了，测试环境windows10 + Mcafee

**Comment by SteveXu9102** [comment] 2023-11-16 18:37
出现相同问题。
在清除下载缓存（删除程序目录下cache文件夹）后解决了问题。

**Comment by YuhangTom** [comment] 2023-11-16 20:52
> 出现相同问题。 在清除下载缓存（删除程序目录下cache文件夹）后解决了问题。 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13382264/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13382265/gui.log) （在 2023-11-17 02:32:28.698 - 02:34:25.662 间进行了上述操作。） 环境：Windows 11 23H2 22635.2700

确实可以了，感谢！

**Comment by ABA2396** [comment] 2023-11-17 06:55
~~与其说是更新v4.27.0-beta.1后每次启动更新游戏资源都失败，不如说是之前都失败了只是用户不知道~~

**Comment by Constrat** [comment] 2023-11-17 07:45
duplicate of #7261

**Comment by Astesia-poi** [comment] 2023-11-17 09:32
> 出现相同问题。 在清除下载缓存（删除程序目录下cache文件夹）后解决了问题。 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13382264/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13382265/gui.log) （在 2023-11-17 02:32:28.698 - 02:34:25.662 间进行了上述操作。） 环境：Windows 11 23H2 22635.2700

确实可以了，谢谢

**Comment by Constrat** [comment] 2023-11-17 09:36
@ABA2396 seems like it can't overwrite files. I tried deleting the cache and this time it updated everything correctly.

**Comment by ABA2396** [comment] 2023-11-17 10:01
> @ABA2396 seems like it can't overwrite files. I tried deleting the cache and this time it updated everything correctly. So I don't think retrying the GET request will change anything

The use of `using` is to prevent the stream from not being closed correctly. We'll have to wait until the update to see if it works or not.

**Closed** 2023-11-17 10:04 UTC
Labels: bug, duplicate

**Comment by Constrat** [comment] 2023-11-17 13:28
Seems like it's working as expected.
