### ISSUE TITLE
MAA keeps abandoning task and retry it for 50 times when running initial recruitment on roguelike mode

### ISSUE THREAD

**Issue by rickle-pick** [MaaAssistantArknights/MaaAssistantArknights#6297] opened 2023-09-10 05:22 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA cannot process the initial recruitment on any roguelike mode e.g. phantom and Mitsuki. After clicking the first voucher, it stops at choosing the operator. No swinging to the left or the right. No attempt to click the operator.  Just stopped at the operator page. Then it abandoned the exploration and start over again. The task looped for 50 times and eventually stopped. My debug folder got spammed by screenshots 

This problem is consistent in all squads and settings. 

This problem showed up after I updated to the latest version for both MAA and arknight.  MAA was functional on phantom roguelike last version,  if my memory severs well, v4.2 MAA before the monster hunter update.
I tried other versions but the problem persists, from v4.19 to v4.23. I suspect it's caused by the game update.  

Here is the error message I suspect. Tried playing around with it but didn't work out

{"class":"asst::ProcessTask","details":{"cur_retry":4,"retry_times":20,"to_be_recognized":["Phantom@Roguelike@MissionFailedFlag2","Phantom@Roguelike@StartExplore"]},"first":["Phantom@Roguelike@Begin"],"pre_task":"Phantom@Roguelike@AbandonConfirm","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1}

Thank you MAA team for making such a helpful tool. I was thinking about giving up this game due to its shitty quality of life. But MAA literally freed me from grinding. You guys are great!

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567569/asst.log)

### Screenshots

![2023-09-10_12-52-17-045_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71882837/7a718e27-5432-49b1-b8e7-18bd82864de3)

### Anthing else?

environment. version v4.23.3（395) on macOS, the forked version of play cover for maa.3
tried automatic resolution and 1080p on play cover graphic setting

**Comment by todanielwang** [comment] 2023-09-10 05:53
Pretty sure this is a duplicate of #6281, which should be fixed by #6294

**Comment by Constrat** [comment] 2023-09-10 10:34
> Pretty sure this is a duplicate of #6281, which should be fixed by #6294

https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6294/commits/c31705f74bb39fb2528814e89d79619de8774927 fixed a different problem.
I'm having a look at this right now

**Closed** 2023-09-10 10:54 UTC
Labels: bug, fixed, module: roguelike, duplicate, macOS
