### ISSUE TITLE
開啟MAA出現錯誤，重新開機、重新下載都無法使用

### ISSUE THREAD

**Issue by LOKI696** [MaaAssistantArknights/MaaAssistantArknights#7603] opened 2023-12-14 22:16 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA 遇到了问题
設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。
已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
解决方案
出现未知错误
详细信息
System.Windows.Markup.XamlParseException: 設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。 ---> System.ArgumentException: 已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
   於 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   於 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   於 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(Object target, Object value)
   於 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   於 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   於 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   於 MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 System.Windows.ResourceDictionary.set_Source(Uri value)
   於 MaaWpfGui.Helper.LocalizationHelper.Load()
   於 MaaWpfGui.Main.Bootstrapper.OnStart()
   於 Stylet.BootstrapperBase.Start(String[] args)
   於 System.Windows.Application.OnStartup(StartupEventArgs e)
   於 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   於 System.Windows.Application.<.ctor>b__1_0(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

出現上述錯誤訊息，重新開機、重新下載都無法使用

已確認C++跟NET均為最新版本，模擬器使用藍疊5

### Log files

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13678877/debug.zip)
發生時間在早上6點

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91353273/4f1aa186-83cc-4c31-b7b1-6a17705c800e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91353273/e1cb7760-8479-40fb-9e01-eb01554e6565)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91353273/d98c64b8-c48f-4dd2-bc8f-077bdcaf721b)

### Anthing else?

使用藍疊5、WIN11 22H2

**Comment by bighead945** [comment] 2023-12-14 22:21
v4.28.0 版本沒問題，可以先載回舊版使用。

**Comment by ms200tswd** [comment] 2023-12-14 23:13
跟你一样的问题

**Comment by Joyce-Ethene** [comment] 2023-12-14 23:26
同样问题。而且还被win11防火墙ban掉了/(ㄒoㄒ)/

**Comment by Bala7651** [comment] 2023-12-14 23:34
還以為只有我有這問題，沒想到也有人開始有了

**Comment by Bala7651** [comment] 2023-12-14 23:35
目前確認下在4.28.0，並且不要按下載更新重新啟動 就能解決問題

**Comment by bighead945** [comment] 2023-12-14 23:36
更新後的問題吧?
話說你們都更新哪種版本?
公測?內測?穩定?

**Comment by Bala7651** [comment] 2023-12-14 23:36
> 更新後的問題吧? 話說你們都更新哪種版本? 公測?內測?穩定?

我個人原本是用公測

**Comment by Joyce-Ethene** [comment] 2023-12-14 23:46
我也用的公测版。
更新之后就有这个报错了
然后我的defender开始嘎嘎报警x 
程序都被隔离了（笑哭x

**Comment by status102** [comment] 2023-12-14 23:57
Duplicate of #7599

**Closed by status102** 2023-12-14 23:57 UTC
Labels: bug, client: WpfGui, module: others

**Comment by ABA2396** [comment] 2023-12-15 01:59
v4.28.2 fixed，可以先把 \config\gui.json 中的 "GUI.Localization" 的值改为 "zh-cn" 升级后换回来
