### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by fatkin1012** [MaaAssistantArknights/MaaAssistantArknights#7606] opened 2023-12-14 23:52 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.
Item has already been added. Key in dictionary: 'TrainingCompleted'  Key being added: 'TrainingCompleted'

### Log files

MAA 遇到了问题
Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.
Item has already been added. Key in dictionary: 'TrainingCompleted'  Key being added: 'TrainingCompleted'
解决方案
出现未知错误
详细信息
System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception. ---> System.ArgumentException: Item has already been added. Key in dictionary: 'TrainingCompleted'  Key being added: 'TrainingCompleted'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(Object target, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at MaaWpfGui.Helper.LocalizationHelper.Load()
   at MaaWpfGui.Main.Bootstrapper.OnStart()
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70193444/48f98670-94c9-4311-892b-cb0668e13657)

**Comment by status102** [comment] 2023-12-14 23:57
Duplicate of #7599

**Closed by status102** 2023-12-14 23:57 UTC
Labels: bug, client: WpfGui, module: others

**Comment by ABA2396** [comment] 2023-12-15 01:58
v4.28.2 fixed，可以先把 \config\gui.json 中的 "GUI.Localization" 的值改为 "zh-cn" 升级后换回来
