### ISSUE TITLE
肉鸽导航路径过于简单，导致在特殊情况下出现的导航失败问题

### ISSUE THREAD

**Issue by msisalnais** [MaaAssistantArknights/MaaAssistantArknights#8601] opened 2024-03-13 15:59 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![Snipaste_2024-03-13_23-36-24](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/683f46dd-7c10-4698-955e-d54af255790e)
![Snipaste_2024-03-13_23-51-15](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/e3258aa4-34f2-49b0-b4e1-8745959d1c64)
[在这种**特殊情况**下出现**无法自动导航到肉鸽**的情况：MAA试图重新导航多次，但一直不成功且没有在日志中提示该错误的发生，我觉得这很可能是bug。
若可行，推荐从**更加可靠的路径**实现肉鸽导航

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2.d057.gf9599282f
Core Version: v5.2.0-beta.2.d057.gf9599282f

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14590367/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14590369/gui.log)

### 截图

![2024-03-13_23-12-53-540_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/9033c592-4924-4d36-96de-76cf43bdadba)
![2024-03-13_23-13-27-657_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/21edd8e5-c1fc-4f4a-a1f6-067896c5b04a)
![2024-03-13_23-14-01-559_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/0492e9a9-cf1b-4991-92c2-a3ebf01ed64c)
![2024-03-13_23-14-35-878_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/eb21f53c-332c-43ff-82ee-b72af231a314)
![2024-03-13_23-15-09-509_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/567f1172-e3db-4c0f-86a8-b023951a9d48)
![2024-03-13_23-15-44-052_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/7f6e486e-4ff5-4aee-9b80-f514398bbea4)
![2024-03-13_23-48-32-564_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/f6ce15f3-6474-406e-9d7b-9ba7b2ba4351)
![2024-03-13_23-49-07-630_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/850f06fd-7b85-4508-9557-41b280a0dae7)
![2024-03-13_23-49-43-300_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/79b6e47e-b1a2-47fc-af5d-0aed69306045)
![2024-03-13_23-50-20-023_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/78b636f8-faf7-4f42-82ff-e7bcbf530bbd)
![2024-03-13_23-50-56-632_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/e9364307-22e0-42b0-9b39-4a916c63446c)
![2024-03-13_23-51-31-587_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/609decd2-4d98-4a38-8d56-fd059f0fa772)
![2024-03-13_23-02-47-504_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/23b3f491-3d0e-43ed-bf96-259e10d07850)
![2024-03-13_23-03-20-018_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/f1b8888b-ddd4-4075-bb2d-486d62cd4a30)
![2024-03-13_23-03-52-444_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/adbc2651-e1e6-4ba8-80a9-c4bbe674825b)
![2024-03-13_23-04-25-274_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/b0c11eb8-12d3-4dc8-bf0c-8e4964b0069a)
![2024-03-13_23-04-58-032_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/268534f2-f664-4eca-8c7f-6f6db911d94e)
![2024-03-13_23-05-31-864_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/cb9b3446-5cce-4193-91e8-ccd102c6b539)
![2024-03-13_23-06-05-681_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/a8869d8f-bf0f-48fe-aa3a-959f034dcf7d)
![2024-03-13_23-06-38-988_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/5e026e91-520a-4bb8-8561-720adbff32ba)
![2024-03-13_23-07-11-941_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/21c1003f-d867-4125-8575-25fbe2e299ca)
![2024-03-13_23-07-44-821_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/febc975b-744a-4d98-8a66-62c903f0e56b)
![2024-03-13_23-08-19-265_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/fbaa376b-10d0-4581-b8af-d7e7fb763f1d)
![2024-03-13_23-08-55-173_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/19b0dff9-6590-4d6a-ac2a-00637a9fa3b1)
![2024-03-13_23-09-29-068_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/f2f9c8d4-05f7-44b5-8463-c4a46af378a7)
![2024-03-13_23-10-03-162_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/b15772be-956f-42b9-8997-9f957560dddd)
![2024-03-13_23-10-37-040_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/6e957551-88bb-469c-8516-34da9efe00db)
![2024-03-13_23-11-11-044_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/8ec3d33f-395b-453f-93a3-23019599b8a9)
![2024-03-13_23-11-45-363_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/52375f23-06bb-495d-89e1-5fc4371449c1)
![2024-03-13_23-12-19-441_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89062285/f9dafba8-3bde-4aea-b49f-550c1bf75cb6)

如你所愿，全是这个截图

**Comment by msisalnais** [comment] 2024-03-13 16:02
*日志中的肉鸽部分是我手动进入肉鸽后MAA才进行的。

**Comment by ABA2396** [comment] 2024-03-13 16:15
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cb859ce6-d3e1-48fc-b4df-d6d6ba7fe588)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/68f902ae-77e8-4da5-90c2-2bed322d0b81)

**Comment by status102** [comment] 2024-03-13 23:56
duplicate of pinned issue

**Closed** 2024-03-13 23:55 UTC
Labels: bug, module: roguelike
