### ISSUE TITLE
新版本提高理智上限之后，博朗台模式在超过135理智仍会等待

### ISSUE THREAD

**Issue by AlearXS** [MaaAssistantArknights/MaaAssistantArknights#11140] opened 2024-11-12 10:31 UTC
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如题

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17715001/gui.json)
[asst.bak.log](https://github.com/user-attachments/files/17715002/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17715004/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17715007/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17715008/gui.log)

### 配置信息

操作系统：Windows 11 家庭中文版 22000.2538
模拟器为mumu12 1920x1080 dpi 280 帧率限制60
未开启截图增强和GPU加速推理

### 截图或录屏

![MuMu12-20241112-182130](https://github.com/user-attachments/assets/aec174c8-35a9-4767-ae0b-350b27ffcb85)

**Comment by Constrat** [comment] 2024-11-12 11:26
Isn't this just a coincidence in numbers? 
You are at 15 sanity, and the potion gives 120, for a total of 135, coincidentally the older sanity cap
You could have been at 0 sanity and the potion giving just 80 (monthly) and it would have still waited.

DrGrandet mode doesn't care about the reaching sanity value, it's just a simple algorithm that chooses to use sanity (whatever value) after the sanity changes by one point.

**Comment by Saratoga-Official** [comment] 2024-11-12 11:31
Duplicate of #11048

**Comment by Constrat** [comment] 2024-11-12 11:32
Oh yeah, https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/11048 is basically my last step.

**Closed** 2024-11-12 11:33 UTC
Labels: bug, duplicate, module: core
