### ISSUE TITLE
Cant start Anihilation JP Client（殲滅が実行できない）

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#1868] opened 2022-09-18 21:35 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Tasks do not initiate combat.
Once back in the lobby, it gets stuck.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9595277/asst.log)

### Screenshots

![image](https://user-images.githubusercontent.com/63186641/190928856-39aaef0b-84cb-4957-841c-a734c3426708.png)

**Comment by MistEO** [comment] 2022-09-19 03:29
In the CN client, you can use the "full commission" for Anihilation combat (I don't know its English name, This is an option to complete the battle directly without waiting), so there is a special identification here. The overseas clients are not different from other combats, so just "Cur/Last".

**Comment by wallsman** [comment] 2022-09-19 03:35
Sorry for the lack of additional information." Cur/Last" works the same.
If start in this state, will get stuck after returning to the lobby.

Task Moving
Cur/last
Anihilation Waiting(Screenshot) - Lobby - PRTS(Stop)

Anihilation
Anihilation Waiting(Screenshot) - Lobby - PRTS - Anihilation Waiting(Stop)

**Comment by wallsman** [comment] 2022-09-26 02:54
4.5.0 move change

Cur/last
Anihilation Waiting(Screenshot) - Lobby - PRTS - Last mission(Not anihilation) - Start

**Comment by wallsman** [comment] 2022-09-26 03:09
![image](https://user-images.githubusercontent.com/63186641/192186377-b4d16815-5a7e-4817-9695-f94e0da7ee0f.png)

**Comment by MistEO** [comment] 2022-11-17 14:13
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2691

**Closed by MistEO** 2022-11-17 14:13 UTC
Labels: bug, module: fight, Client: JP
