### ISSUE TITLE
Windows误报v4.28.1为木马 Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Chococar-NSW** [MaaAssistantArknights/MaaAssistantArknights#7600] opened 2023-12-14 19:36 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从v4.28.0更新到v4.28.1之后就会误报，也试过直接装v4.28.1，误报后还顺带把v4.28.0的压缩档也当成木马移除掉了
但v4.28.1的压缩档不会

### 日志文件

没有

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/79390577/a24cd953-c9f0-4411-b9c4-15a2b7f13820)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/79390577/fec6da15-39ac-4103-af96-4e5755c816c2)

**Comment by RunjieTomYi** [comment] 2023-12-14 19:47
Same problems with MAA v4.28.1 on Windows 10 Pro. Older versions of MAA (4.15) not affected.

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64788721/057e3681-448b-4a39-922b-2a3feca7ed0a)

**Comment by Constrat** [comment] 2023-12-14 20:22
The issue is even pinned. Don't open useless issues. 
Duplicate of #6662

**Closed by Constrat** 2023-12-14 20:22 UTC
Labels: bug, ambiguous

**Comment by Chococar-NSW** [comment] 2023-12-15 05:20
If I can comment at pinned issue,so this issue like a reminder for anyone.
You guys even not metion Trojan:Win32/Wacatac.B!ml in #6662
