### ISSUE TITLE
日服愚人号复刻，刷理智失败

### ISSUE THREAD

**Issue by haibaoAzarashi** [MaaAssistantArknights/MaaAssistantArknights#7440] opened 2023-11-30 11:39 UTC
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打了一把SN-9，试图让maa重复刷这关，结果直接显示任务出错，猜测是ui相关问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13512229/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13512230/gui.log)

### 截图

![QQ截图20231130203728](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/a806b9cb-3274-48d2-8a25-3d4870887442)
![QQ截图20231130203855](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/ededd95f-c9ec-48d9-97a3-1dc6622d944b)
![QQ截图20231130203904](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/f501c17b-7b70-47da-80ba-8879ecb8a155)

**Comment by status102** [comment] 2023-11-30 11:49
Duplicate of #7421

**Comment by Constrat** [comment] 2023-11-30 13:19
@status102 if they are duplicates, just close then as not planned.
Especially if the main issue has already been fixed.

**Closed** 2023-11-30 13:19 UTC
Labels: bug, module: fight, duplicate, Client: JP

**Comment by status102** [comment] 2023-11-30 13:21
> @status102 if they are duplicates, just close then as not planned. Especially if the main issue has already been fixed.

oh, I forgot that, sorry
