### ISSUE TITLE
解决Windows Defender 误报特洛伊木马问题的一种可行方案

### ISSUE THREAD

**Issue by Heart-of-engine** [MaaAssistantArknights/MaaAssistantArknights#7690] opened 2023-12-18 14:40 UTC
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e29a7cd4-a372-4973-9ad9-273b36ae6e02)

_Originally posted by @ABA2396 in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662#issuecomment-1859202374_
 
该方法确实可行，大家也可以来尝试！

**Comment by Heart-of-engine** [comment] 2023-12-18 14:44
同时最好在这里也勾选上“允许在此设备上”
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71398110/6c42bea0-bc52-46e9-86b3-4a6051709fab)

**Comment by status102** [comment] 2023-12-18 14:50
Duplicate of #6662

**Closed by status102** 2023-12-18 14:50 UTC
Labels: ambiguous
