### ISSUE TITLE
[KR]BOSS Rush #4 Copilot 

### ISSUE THREAD

**Issue by xczsonn** [MaaAssistantArknights/MaaAssistantArknights#10337] opened 2024-08-23 00:22 UTC
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

 It seems that Copilot is not working properly in certain environments. The same issue occurred in Boss Rush #3, and it's happening again in #4. After deploying only one operator, it ignores commands to deploy other operators, and the operation fails as a result.

### Version

Resource Version: 불로 비춰주소서 (재개방)
UI Version: v5.6.0-beta.1.d069.g046b3329e
Core Version: v5.6.0-beta.1.d069.g046b3329e

### Log files

https://gofile.io/d/StZNVp

### Configuration information

https://gofile.io/d/pl8zsr

### Anthing else?

1920x1080, 1280x720 both not work

**Comment by Manicsteiner** [comment] 2024-08-23 04:14
Duplicate of #10282
Maybe Yostar made some small changes to the map that caused these problems

**Closed by Manicsteiner** 2024-08-23 04:14 UTC
Labels: bug, module: copilot
