### ISSUE TITLE
对于肉鸽运行方式的优化建议

### ISSUE THREAD

**Issue by TobyLi223** [MaaAssistantArknights/MaaAssistantArknights#9764] opened 2024-07-19 13:50 UTC
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

1.参考其他脚本，特别是arklights，在一些基础操作中改用效率更高的识别和点击方式，以减少战斗外的时间消耗。
2.建立个人本地的干员数据库，定期更新，配合对局内情况的识别和计算快速优化招募选择界面的占用时间。
3.招募券选择增加自定义抓位以保留希望避免一些脑溢血的操作
4.增加对新月度小队，一局内从人到MAA的接管功能。

### 其他内容

无

**Comment by Constrat** [comment] 2024-07-19 15:17
These are all great ideas, but unfortunately we already have plenty "product managers". The issue is to implement all these ideas.
In a way, it's like suggesting: just make MAA run faster and in a more optimized way. The issue arises in this conception: the problem is not bringing up the idea, but implementing it in a logical way.

Especially in the roguelike where a human mind will obviously make the correct choices because we "think". Allowing MAA to do all that would almost make in an AI, which, let's be honest, it's completely out of scope.

MAA started as a daily mission claimer, basically something a bit better than a macro. And now we can clear all I.S. themes without a lot of issues.

**Closed by Constrat** 2024-07-19 15:17 UTC
Labels: enhancement, module: roguelike

**Comment by Saratoga-Official** [comment] 2024-07-21 08:39
想法很好，做起来很难，应该说没人做，工作量还大，除非你想自己学着给maa做这几点，不然就遥遥无期
